# config.yaml

# General settings
project:
  name: Cement-Mixer-IoT-Data-Pipeline
  version: 1.0.0

# Logging configuration
logging:
  level: INFO
  file: logs/app.log

# Database configuration
database:
  host: localhost
  port: 5432
  name: cement_mixer_db
  user: db_user
  password: db_password

# MQTT Broker configuration
mqtt:
  broker: mqtt.example.com
  port: 1883
  topic: cement/mixer/data
  client_id: cement_mixer_client

# Sensor data processing
sensors:
  temperature:
    unit: celsius
    threshold: 75
  humidity:
    unit: percent
    threshold: 60
  vibration:
    unit: g
    threshold: 2.5

# Data pipeline settings
pipeline:
  batch_size: 100
  interval: 60  # in seconds

# Alerting configuration
alerts:
  email:
    enabled: true
    smtp_server: smtp.example.com
    port: 587
    from: alert@example.com
    to: admin@example.com
  sms:
    enabled: false
    provider: twilio
    account_sid: your_account_sid
    auth_token: your_auth_token
    from: +1234567890
    to: +0987654321